platformName: 'Android'
platformVersion: '12'
deviceName: 'Sony Xperia 1 II'
udid: 'QV71159E3F'
realDevice: 'true'
appPackage: 'com.info.h57s45h'
appActivity: 'com.zoontek.rnbootsplash.RNBootSplashActivity'
driver: 'http://127.0.0.1:4723/wd/hub'
unicodeKeyboard: true
resetKeyboard: true
newSessionWaitTimeout: 300
newCommandTimeout: 5
endSessionWaitTimeout: 300

